### ISSUE TITLE
add npm also to start

### ISSUE THREAD

**Issue by tpaivaa** [sNAtttu/CottageNodeJsBackend#1]
Tomis-MBP:test tpaivaa$ git clone git@github.com:sNAtttu/CottageNodeJsBackend.git
Cloning into 'CottageNodeJsBackend'...
remote: Counting objects: 41, done.
remote: Compressing objects: 100% (33/33), done.
remote: Total 41 (delta 13), reused 30 (delta 7), pack-reused 0
Receiving objects: 100% (41/41), 64.07 KiB | 222.00 KiB/s, done.
Resolving deltas: 100% (13/13), done.
Tomis-MBP:test tpaivaa$ cd CottageNodeJsBackend/
Tomis-MBP:CottageNodeJsBackend tpaivaa$ ls
Dockerfile		controllers		package-lock.json
README.md		docker-compose.yml	package.json
app.js			models			yarn.lock
Tomis-MBP:CottageNodeJsBackend tpaivaa$ yarn install
-bash: yarn: command not found
Tomis-MBP:CottageNodeJsBackend tpaivaa$ npm install
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

> fsevents@1.2.4 install /Users/tpaivaa/Dev/test/CottageNodeJsBackend/node_modules/fsevents
> node install

[fsevents] Success: "/Users/tpaivaa/Dev/test/CottageNodeJsBackend/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> nodemon@1.17.5 postinstall /Users/tpaivaa/Dev/test/CottageNodeJsBackend/node_modules/nodemon
> node bin/postinstall || exit 0

Love nodemon? You can now support the project via the open collective:
 > https://opencollective.com/nodemon/donate

npm WARN nodecottage@1.0.0 No repository field.

added 814 packages in 33.478s

   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 5.10.0 → 6.1.0    │
   │      Run npm i -g npm to update      │
   │                                      │
   ╰──────────────────────────────────────╯

Tomis-MBP:CottageNodeJsBackend tpaivaa$ docker-compose build
mongo uses an image, skipping
Building web
Step 1/6 : FROM mhart/alpine-node:9
9: Pulling from mhart/alpine-node
c77918da3c72: Pull complete
Digest: sha256:3c3f7e30beb78b26a602f12da483d4fa0132e6d2b625c3c1b752c8a8f0fbd359
Status: Downloaded newer image for mhart/alpine-node:9
 ---> bd69a82c390b
Step 2/6 : ADD . /app
 ---> a81a0990cdf8
Step 3/6 : WORKDIR /app
Removing intermediate container de97f6bf90e7
 ---> e202449e1947
Step 4/6 : RUN yarn global add nodemon
 ---> Running in 013fe2ae4db9
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "nodemon@1.17.5" with binaries:
      - nodemon
Done in 9.33s.
Removing intermediate container 013fe2ae4db9
 ---> 96eec4aaea7c
Step 5/6 : RUN yarn install
 ---> Running in f0e7c29b901c
^[[Byarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 27.35s.
Removing intermediate container f0e7c29b901c
 ---> 9764162c8ff5
Step 6/6 : RUN yarn test
 ---> Running in 263340baf565
yarn run v1.5.1
$ jest
PASS controllers/__tests__/listController.test.js
  Itemlist route
    ? Initializes correctly (3ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.179s
Ran all test suites.
Done in 2.93s.
Removing intermediate container 263340baf565
 ---> 6b4f7a909526
Successfully built 6b4f7a909526
Successfully tagged cottagenodejsbackend_web:latest
Tomis-MBP:CottageNodeJsBackend tpaivaa$ docker-compose up
Creating network "cottagenodejsbackend_default" with the default driver
Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
4d0d76e05f3c: Pull complete
d3e8f2a80d9c: Pull complete
fa1dfbce34f0: Pull complete
9c46dfce21d0: Pull complete
5108b7b81738: Pull complete
f96cba0bb653: Pull complete
11707d2d22ac: Pull complete
8e8c0aaadd20: Pull complete
23c7bba6fd7d: Pull complete
3f745addabe8: Pull complete
Digest: sha256:3a09cd85fb4e76f1d5832f9ea1d4e7481f76e807389b7d8ea6ac4d4ba96f83e5
Status: Downloaded newer image for mongo:latest
Creating cottagenodejsbackend_mongo_1 ... done
Creating cottagenodejsbackend_web_1   ... done
Attaching to cottagenodejsbackend_mongo_1, cottagenodejsbackend_web_1
mongo_1  | 2018-06-20T18:28:15.671+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=2a5bd67666a2
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] db version v3.6.5
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] git version: a20ecd3e3a174162052ff99913bc2ca9a839d618
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] modules: none
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] build environment:
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten]     distmod: debian81
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1  | 2018-06-20T18:28:15.672+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongo_1  | 2018-06-20T18:28:15.673+0000 I STORAGE  [initandlisten] 
mongo_1  | 2018-06-20T18:28:15.673+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1  | 2018-06-20T18:28:15.673+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1  | 2018-06-20T18:28:15.673+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=487M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),cache_cursors=false,log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1  | 2018-06-20T18:28:16.443+0000 I STORAGE  [initandlisten] WiredTiger message [1529519296:443283][1:0x7f35ee238a00], txn-recover: Set global recovery timestamp: 0
mongo_1  | 2018-06-20T18:28:16.491+0000 I CONTROL  [initandlisten] 
mongo_1  | 2018-06-20T18:28:16.491+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1  | 2018-06-20T18:28:16.491+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1  | 2018-06-20T18:28:16.491+0000 I CONTROL  [initandlisten] 
mongo_1  | 2018-06-20T18:28:16.492+0000 I STORAGE  [initandlisten] createCollection: admin.system.version with provided UUID: 3042498c-0448-40cb-8d69-5ed75a5cdb3c
mongo_1  | 2018-06-20T18:28:16.515+0000 I COMMAND  [initandlisten] setting featureCompatibilityVersion to 3.6
mongo_1  | 2018-06-20T18:28:16.520+0000 I STORAGE  [initandlisten] createCollection: local.startup_log with generated UUID: defeb8e8-50cc-4b1b-932a-ed9b47187fc0
mongo_1  | 2018-06-20T18:28:16.540+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1  | 2018-06-20T18:28:16.541+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
web_1    | [nodemon] 1.17.5
web_1    | [nodemon] to restart at any time, enter `rs`
web_1    | [nodemon] watching: *.*
web_1    | [nodemon] starting `node --inspect app.js`
web_1    | Debugger listening on ws://127.0.0.1:9229/226fa0bf-2bd3-402e-bbca-2700cbbea575
web_1    | For help see https://nodejs.org/en/docs/inspector
web_1    | info: Listening on port: 3000
mongo_1  | 2018-06-20T18:28:22.464+0000 I NETWORK  [listener] connection accepted from 172.19.0.3:40264 #1 (1 connection now open)
mongo_1  | 2018-06-20T18:28:22.472+0000 I NETWORK  [conn1] received client metadata from 172.19.0.3:40264 conn1: { driver: { name: "nodejs", version: "3.0.10" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.9.87-linuxkit-aufs" }, platform: "Node.js v9.11.1, LE, mongodb-core: 3.0.9" }

**Comment by sNAtttu** [comment]
### Thanks for reporting this.
I will do this on next release on september 2019!
